// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
void compass1_Animation( lv_obj_t *TargetObject, int delay);
void compass2_Animation( lv_obj_t *TargetObject, int delay);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_backend;
lv_obj_t *ui_ContainerDIr;
lv_obj_t *ui_compass;
lv_obj_t *ui_imgDirZ;
lv_obj_t *ui_topLeft;
lv_obj_t *ui_textTIme;
lv_obj_t *ui_ImageGpsDisc;
lv_obj_t *ui_imgGps;
lv_obj_t *ui_textGpsHz;
lv_obj_t *ui_textGpsNu;
lv_obj_t *ui_topRight;
lv_obj_t *ui_imgBle;
lv_obj_t *ui_imgWificon;
lv_obj_t *ui_imgWifiOk;
lv_obj_t *ui_imgWifi;
lv_obj_t *ui_imgBleDiscon;
lv_obj_t *ui_textBatPercent;
lv_obj_t *ui_imageBat;
void ui_event_SliderBat( lv_event_t * e);
lv_obj_t *ui_SliderBat;
lv_obj_t *ui_textBat;
lv_obj_t *ui_ContainerSpeed;
lv_obj_t *ui_imgSpeed0;
lv_obj_t *ui_imgSpeed1;
void ui_event_SliderSpeed( lv_event_t * e);
lv_obj_t *ui_SliderSpeed;
lv_obj_t *ui_imgKMH;
void ui_event_textSpeed( lv_event_t * e);
lv_obj_t *ui_textSpeed;
lv_obj_t *ui_ContainerGyro;
lv_obj_t *ui_imgGyro0;
void ui_event_SliderGyro( lv_event_t * e);
lv_obj_t *ui_SliderGyro;
lv_obj_t *ui_textGyroVal;
lv_obj_t *ui_textGyroTopLeft;
lv_obj_t *ui_textGyroTopRight;
lv_obj_t *ui_botLeft;
lv_obj_t *ui_textTrip;
lv_obj_t *ui_ContainerGps;
lv_obj_t *ui_textLocation;
lv_obj_t *ui_imgLocation;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_frame_[1] = {&ui_img_frame_1_png};
const lv_img_dsc_t *ui_imgset_42937250[1] = {&ui_img_1142323638};
const lv_img_dsc_t *ui_imgset_bluetooth_[1] = {&ui_img_bluetooth_1_png};
const lv_img_dsc_t *ui_imgset_dir_img_[1] = {&ui_img_dir_img_30_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void compass1_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 2000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, 40 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_linear);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}
void compass2_Animation( lv_obj_t *TargetObject, int delay)
{
ui_anim_user_data_t *PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
PropertyAnimation_0_user_data->target = TargetObject;
PropertyAnimation_0_user_data->val = -1;
lv_anim_t PropertyAnimation_0;
lv_anim_init(&PropertyAnimation_0);
lv_anim_set_time(&PropertyAnimation_0, 2000);
lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_x );
lv_anim_set_values(&PropertyAnimation_0, 0, -40 );
lv_anim_set_path_cb( &PropertyAnimation_0, lv_anim_path_ease_out);
lv_anim_set_delay( &PropertyAnimation_0, delay + 0 );
lv_anim_set_deleted_cb( &PropertyAnimation_0, _ui_anim_callback_free_user_data );
lv_anim_set_playback_time(&PropertyAnimation_0, 0);
lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
 lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
lv_anim_set_early_apply( &PropertyAnimation_0, false );
 lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_x );
lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_SliderBat( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_textBat, target, "", "");
}
}
void ui_event_SliderSpeed( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_textSpeed, target, "", "");
}
}
void ui_event_textSpeed( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_increment( ui_SliderSpeed, 1, LV_ANIM_ON);
}
}
void ui_event_SliderGyro( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_textGyroVal, target, "", "");
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
