// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

void compass1_Animation( lv_obj_t *TargetObject, int delay);
void compass2_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_backend;
extern lv_obj_t *ui_topLeft;
extern lv_obj_t *ui_textTime;
extern lv_obj_t *ui_textGpsHz;
extern lv_obj_t *ui_imgGps;
extern lv_obj_t *ui_textGpsNu;
extern lv_obj_t *ui_TopMid;
extern lv_obj_t *ui_Compass;
extern lv_obj_t *ui_topRight;
extern lv_obj_t *ui_imgBle;
extern lv_obj_t *ui_imgWifi;
extern lv_obj_t *ui_textBatPercent;
extern lv_obj_t *ui_imageBat;
void ui_event_SliderBat( lv_event_t * e);
extern lv_obj_t *ui_SliderBat;
extern lv_obj_t *ui_textBat;
extern lv_obj_t *ui_ContainerSpeed;
extern lv_obj_t *ui_imgSpeed0;
extern lv_obj_t *ui_imgSpeed1;
void ui_event_SliderSpeed( lv_event_t * e);
extern lv_obj_t *ui_SliderSpeed;
extern lv_obj_t *ui_imgKMH;
void ui_event_textSpeed( lv_event_t * e);
extern lv_obj_t *ui_textSpeed;
extern lv_obj_t *ui_ContainerGyro;
extern lv_obj_t *ui_imgGyro0;
void ui_event_SliderGyro( lv_event_t * e);
extern lv_obj_t *ui_SliderGyro;
extern lv_obj_t *ui_textGyroVal;
extern lv_obj_t *ui_textGyroTopLeft;
extern lv_obj_t *ui_textGyroTopRight;
extern lv_obj_t *ui_botLeft;
extern lv_obj_t *ui_textTrip;
extern lv_obj_t *ui_ContainerGps;
extern lv_obj_t *ui_textLocation;
extern lv_obj_t *ui_imgLocation;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_background_png);   // assets/background.png
LV_IMG_DECLARE( ui_img_weixing_ok_png);   // assets/weixing_ok.png
LV_IMG_DECLARE( ui_img_bluetooth_1_png);   // assets/bluetooth 1.png
LV_IMG_DECLARE( ui_img_wifiok_png);   // assets/wifiok.png
LV_IMG_DECLARE( ui_img_bat_png);   // assets/bat.png
LV_IMG_DECLARE( ui_img_guage_bg_png);   // assets/guage bg.png
LV_IMG_DECLARE( ui_img_speedcolor_png);   // assets/speedColor.png
LV_IMG_DECLARE( ui_img_speednu_png);   // assets/speedNu.png
LV_IMG_DECLARE( ui_img_h_png);   // assets/H.png
LV_IMG_DECLARE( ui_img_gyro_png);   // assets/gyro.png
LV_IMG_DECLARE( ui_img_gyrobackend_png);   // assets/gyroBackend.png
LV_IMG_DECLARE( ui_img_1142323638);   // assets/GPS显示 1.png
LV_IMG_DECLARE( ui_img_frame_1_png);   // assets/Frame 1.png
LV_IMG_DECLARE( ui_img_dir_img_30_png);   // assets/dir_img_30.png


LV_FONT_DECLARE( ui_font_Black_Ops_One);
LV_FONT_DECLARE( ui_font_Black_Ops_One_14);
LV_FONT_DECLARE( ui_font_Black_Ops_One_22);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
