; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
extra_scripts = 
	pre:get_version.py
upload_speed = 115200
upload_flags = 
	--before=default_reset
	--after=hard_reset



[env:esp32-air780eg]
platform = espressif32
board = esp32dev
framework = arduino
board_build.partitions = partitions_ota.csv
lib_deps = 
	mikalhart/TinyGPSPlus
	plerup/EspSoftwareSerial@^8.1.0
	lewisxhe/SensorLib@^0.2.0
	bblanchon/ArduinoJson@^6.21.3
	fastled/FastLED@^3.5.0
	https://github.com/Granddyser/QMC5883P.git
	arduino-libraries/Madgwick@^1.2.0
	https://github.com/motoboxcn/Air780EG.git
build_flags = 
	-D CHARGING_STATUS_PIN=17
	-D BAT_PIN=36
	-D RTC_INT_PIN=16
	-D IMU_INT_PIN=34
	-D IIC_SDA_PIN=26
	-D IIC_SCL_PIN=25
	-D ENABLE_AIR780EG
	-D ENABLE_IMU
	; -D ENABLE_IMU_FUSION
	-D AIR780EG_LOG_VERBOSE_ENABLED=true
	-D GSM_RX_PIN=19
	-D GSM_TX_PIN=18
	-D GSM_EN=5
	-D PWM_LED_PIN=33


[env:dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = partitions_ota.csv
lib_deps = 
	mikalhart/TinyGPSPlus
	plerup/EspSoftwareSerial@^8.1.0
	lewisxhe/SensorLib@^0.2.0
	bblanchon/ArduinoJson@^6.21.3
	fastled/FastLED@^3.5.0
	https://github.com/Granddyser/QMC5883P.git
	arduino-libraries/Madgwick@^1.2.0
build_flags = 
	-D CHARGING_STATUS_PIN=17
	-D BAT_PIN=2
	; -D RTC_INT_PIN=5
	-D IMU_INT_PIN=4
	-D IIC_SDA_PIN=17
	-D IIC_SCL_PIN=16
	-D IIC_SDA_GY=9
	-D IIC_SCL_GY=10
	-D ENABLE_AIR780EG
	-D ENABLE_IMU
	-D ENABLE_COMPASS
	; -D ENABLE_SLEEP
	; -D ENABLE_IMU_FUSION
	; -D AIR780EG_LOG_VERBOSE_ENABLED=true
	-D GSM_RX_PIN=14
	-D GSM_TX_PIN=13
	-D GSM_EN=12
	-D PWM_LED_PIN=48
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1