// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Screen1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x201F1F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );

ui_backend = lv_img_create(ui_Screen1);
lv_img_set_src(ui_backend, &ui_img_background_png);
lv_obj_set_width( ui_backend, LV_SIZE_CONTENT);  /// 320
lv_obj_set_height( ui_backend, LV_SIZE_CONTENT);   /// 172
lv_obj_set_align( ui_backend, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_backend, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_backend, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_topLeft = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_topLeft);
lv_obj_set_width( ui_topLeft, 221);
lv_obj_set_height( ui_topLeft, 36);
lv_obj_clear_flag( ui_topLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_textTime = lv_label_create(ui_topLeft);
lv_obj_set_width( ui_textTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_textTime, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_textTime,"2024-09-05 12:12:12");
lv_obj_set_style_text_color(ui_textTime, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textTime, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_textGpsHz = lv_label_create(ui_topLeft);
lv_obj_set_width( ui_textGpsHz, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textGpsHz, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_textGpsHz, 5 );
lv_obj_set_y( ui_textGpsHz, 0 );
lv_obj_set_align( ui_textGpsHz, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_textGpsHz,"10");
lv_obj_set_style_text_color(ui_textGpsHz, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textGpsHz, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textGpsHz, &ui_font_Black_Ops_One_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgGps = lv_img_create(ui_topLeft);
lv_img_set_src(ui_imgGps, &ui_img_weixing_ok_png);
lv_obj_set_width( ui_imgGps, LV_SIZE_CONTENT);  /// 15
lv_obj_set_height( ui_imgGps, LV_SIZE_CONTENT);   /// 14
lv_obj_set_x( ui_imgGps, 30 );
lv_obj_set_y( ui_imgGps, 0 );
lv_obj_set_align( ui_imgGps, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_imgGps, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgGps, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_textGpsNu = lv_label_create(ui_topLeft);
lv_obj_set_width( ui_textGpsNu, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textGpsNu, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_textGpsNu, 55 );
lv_obj_set_y( ui_textGpsNu, 0 );
lv_obj_set_align( ui_textGpsNu, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_textGpsNu,"10");
lv_obj_set_style_text_color(ui_textGpsNu, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textGpsNu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textGpsNu, &ui_font_Black_Ops_One_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TopMid = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_TopMid);
lv_obj_set_width( ui_TopMid, 73);
lv_obj_set_height( ui_TopMid, 39);
lv_obj_set_x( ui_TopMid, -18 );
lv_obj_set_y( ui_TopMid, 36 );
lv_obj_set_align( ui_TopMid, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_TopMid, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Composs = lv_label_create(ui_TopMid);
lv_obj_set_width( ui_Composs, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Composs, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Composs, LV_ALIGN_CENTER );
lv_label_set_text(ui_Composs,"NE");
lv_obj_set_style_text_color(ui_Composs, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Composs, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Composs, &ui_font_Black_Ops_One_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_topRight = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_topRight);
lv_obj_set_width( ui_topRight, 80);
lv_obj_set_height( ui_topRight, 30);
lv_obj_set_x( ui_topRight, 0 );
lv_obj_set_y( ui_topRight, 2 );
lv_obj_set_align( ui_topRight, LV_ALIGN_TOP_RIGHT );
lv_obj_clear_flag( ui_topRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgBle = lv_img_create(ui_topRight);
lv_img_set_src(ui_imgBle, &ui_img_bluetooth_1_png);
lv_obj_set_width( ui_imgBle, LV_SIZE_CONTENT);  /// 11
lv_obj_set_height( ui_imgBle, LV_SIZE_CONTENT);   /// 11
lv_obj_set_align( ui_imgBle, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_imgBle, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgBle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgWifi = lv_img_create(ui_topRight);
lv_img_set_src(ui_imgWifi, &ui_img_wifiok_png);
lv_obj_set_width( ui_imgWifi, LV_SIZE_CONTENT);  /// 11
lv_obj_set_height( ui_imgWifi, LV_SIZE_CONTENT);   /// 11
lv_obj_set_x( ui_imgWifi, 11 );
lv_obj_set_y( ui_imgWifi, 0 );
lv_obj_set_align( ui_imgWifi, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_imgWifi, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgWifi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_imgWifi, lv_color_hex(0x0A0B0A), LV_PART_MAIN| LV_STATE_DISABLED);
lv_obj_set_style_img_recolor_opa(ui_imgWifi, 0, LV_PART_MAIN| LV_STATE_DISABLED);

ui_textBatPercent = lv_label_create(ui_topRight);
lv_obj_set_width( ui_textBatPercent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textBatPercent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_textBatPercent, 9 );
lv_obj_set_y( ui_textBatPercent, 0 );
lv_obj_set_align( ui_textBatPercent, LV_ALIGN_CENTER );
lv_label_set_text(ui_textBatPercent,"%");
lv_obj_set_style_text_color(ui_textBatPercent, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textBatPercent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textBatPercent, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imageBat = lv_img_create(ui_topRight);
lv_img_set_src(ui_imageBat, &ui_img_bat_png);
lv_obj_set_width( ui_imageBat, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_imageBat, LV_SIZE_CONTENT);   /// 11
lv_obj_set_align( ui_imageBat, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_imageBat, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imageBat, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SliderBat = lv_slider_create(ui_imageBat);
lv_slider_set_value( ui_SliderBat, 100, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderBat)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderBat, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderBat, 15);
lv_obj_set_height( ui_SliderBat, 7);
lv_obj_set_x( ui_SliderBat, -1 );
lv_obj_set_y( ui_SliderBat, 0 );
lv_obj_set_align( ui_SliderBat, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_SliderBat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SliderBat, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderBat, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_SliderBat, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SliderBat, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderBat, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_SliderBat, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SliderBat, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderBat, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_textBat = lv_label_create(ui_topRight);
lv_obj_set_width( ui_textBat, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textBat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_textBat, -8 );
lv_obj_set_y( ui_textBat, 0 );
lv_obj_set_align( ui_textBat, LV_ALIGN_CENTER );
lv_label_set_text(ui_textBat,"100");
lv_obj_set_style_text_color(ui_textBat, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textBat, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textBat, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerSpeed = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_ContainerSpeed);
lv_obj_set_width( ui_ContainerSpeed, 302);
lv_obj_set_height( ui_ContainerSpeed, 106);
lv_obj_set_x( ui_ContainerSpeed, -1 );
lv_obj_set_y( ui_ContainerSpeed, 6 );
lv_obj_set_align( ui_ContainerSpeed, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ContainerSpeed, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgSpeed0 = lv_img_create(ui_ContainerSpeed);
lv_img_set_src(ui_imgSpeed0, &ui_img_guage_bg_png);
lv_obj_set_width( ui_imgSpeed0, LV_SIZE_CONTENT);  /// 289
lv_obj_set_height( ui_imgSpeed0, LV_SIZE_CONTENT);   /// 78
lv_obj_set_align( ui_imgSpeed0, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_imgSpeed0, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgSpeed0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_imgSpeed0, &ui_img_speedcolor_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_imgSpeed1 = lv_img_create(ui_ContainerSpeed);
lv_img_set_src(ui_imgSpeed1, &ui_img_speednu_png);
lv_obj_set_width( ui_imgSpeed1, LV_SIZE_CONTENT);  /// 297
lv_obj_set_height( ui_imgSpeed1, LV_SIZE_CONTENT);   /// 81
lv_obj_set_align( ui_imgSpeed1, LV_ALIGN_TOP_MID );
lv_obj_add_flag( ui_imgSpeed1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgSpeed1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SliderSpeed = lv_slider_create(ui_ContainerSpeed);
lv_slider_set_range(ui_SliderSpeed, 0,199);
lv_slider_set_value( ui_SliderSpeed, 299, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderSpeed)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderSpeed, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderSpeed, 300);
lv_obj_set_height( ui_SliderSpeed, 92);
lv_obj_set_align( ui_SliderSpeed, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_SliderSpeed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SliderSpeed, lv_color_hex(0x2D2D2D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderSpeed, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SliderSpeed, &ui_img_guage_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_opa(ui_SliderSpeed, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor(ui_SliderSpeed, lv_color_hex(0x4040FF), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_recolor_opa(ui_SliderSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_SliderSpeed, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SliderSpeed, lv_color_hex(0x292C30), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderSpeed, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SliderSpeed, &ui_img_speedcolor_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_SliderSpeed, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SliderSpeed, lv_color_hex(0x292C31), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderSpeed, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_imgKMH = lv_img_create(ui_ContainerSpeed);
lv_img_set_src(ui_imgKMH, &ui_img_h_png);
lv_obj_set_width( ui_imgKMH, LV_SIZE_CONTENT);  /// 46
lv_obj_set_height( ui_imgKMH, LV_SIZE_CONTENT);   /// 14
lv_obj_set_x( ui_imgKMH, 12 );
lv_obj_set_y( ui_imgKMH, 3 );
lv_obj_set_align( ui_imgKMH, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_imgKMH, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgKMH, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_textSpeed = lv_label_create(ui_ContainerSpeed);
lv_obj_set_width( ui_textSpeed, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textSpeed, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_textSpeed, 5 );
lv_obj_set_y( ui_textSpeed, 0 );
lv_label_set_text(ui_textSpeed,"199");
lv_label_set_recolor(ui_textSpeed,"true");
lv_obj_set_style_text_color(ui_textSpeed, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textSpeed, &ui_font_Black_Ops_One, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerGyro = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_ContainerGyro);
lv_obj_set_width( ui_ContainerGyro, 159);
lv_obj_set_height( ui_ContainerGyro, 53);
lv_obj_set_x( ui_ContainerGyro, 71 );
lv_obj_set_y( ui_ContainerGyro, 29 );
lv_obj_set_align( ui_ContainerGyro, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ContainerGyro, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_imgGyro0 = lv_img_create(ui_ContainerGyro);
lv_img_set_src(ui_imgGyro0, &ui_img_gyro_png);
lv_obj_set_width( ui_imgGyro0, LV_SIZE_CONTENT);  /// 146
lv_obj_set_height( ui_imgGyro0, LV_SIZE_CONTENT);   /// 40
lv_obj_set_align( ui_imgGyro0, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_imgGyro0, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgGyro0, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_imgGyro0, &ui_img_gyrobackend_png, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_SliderGyro = lv_slider_create(ui_ContainerGyro);
lv_slider_set_range(ui_SliderGyro, -68,68);
lv_slider_set_mode(ui_SliderGyro, LV_SLIDER_MODE_SYMMETRICAL);
lv_slider_set_value( ui_SliderGyro, 90, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderGyro)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderGyro, -90, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderGyro, 146);
lv_obj_set_height( ui_SliderGyro, 40);
lv_obj_set_align( ui_SliderGyro, LV_ALIGN_BOTTOM_MID );
lv_obj_set_style_radius(ui_SliderGyro, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SliderGyro, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderGyro, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SliderGyro, &ui_img_gyro_png, LV_PART_MAIN | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_SliderGyro, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SliderGyro, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderGyro, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SliderGyro, &ui_img_gyrobackend_png, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_radius(ui_SliderGyro, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SliderGyro, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SliderGyro, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_textGyroVal = lv_label_create(ui_ContainerGyro);
lv_obj_set_width( ui_textGyroVal, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textGyroVal, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_textGyroVal, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_textGyroVal,"68");
lv_obj_set_style_text_color(ui_textGyroVal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textGyroVal, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_textGyroVal, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textGyroVal, &ui_font_Black_Ops_One_22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_textGyroTopLeft = lv_label_create(ui_ContainerGyro);
lv_obj_set_width( ui_textGyroTopLeft, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textGyroTopLeft, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_textGyroTopLeft, -18 );
lv_obj_set_y( ui_textGyroTopLeft, 0 );
lv_obj_set_align( ui_textGyroTopLeft, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_textGyroTopLeft,"-68°");
lv_obj_set_style_text_color(ui_textGyroTopLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textGyroTopLeft, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_textGyroTopLeft, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textGyroTopLeft, &ui_font_Black_Ops_One_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_textGyroTopRight = lv_label_create(ui_ContainerGyro);
lv_obj_set_width( ui_textGyroTopRight, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textGyroTopRight, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_textGyroTopRight, 18 );
lv_obj_set_y( ui_textGyroTopRight, 0 );
lv_obj_set_align( ui_textGyroTopRight, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_textGyroTopRight,"32°");
lv_obj_set_style_text_color(ui_textGyroTopRight, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textGyroTopRight, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_textGyroTopRight, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textGyroTopRight, &ui_font_Black_Ops_One_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_botLeft = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_botLeft);
lv_obj_set_width( ui_botLeft, 80);
lv_obj_set_height( ui_botLeft, 30);
lv_obj_set_align( ui_botLeft, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_botLeft, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_textTrip = lv_label_create(ui_botLeft);
lv_obj_set_width( ui_textTrip, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textTrip, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_textTrip, LV_ALIGN_CENTER );
lv_label_set_text(ui_textTrip,"Trip: 1234");
lv_obj_set_style_text_color(ui_textTrip, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textTrip, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textTrip, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerGps = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_ContainerGps);
lv_obj_set_width( ui_ContainerGps, 177);
lv_obj_set_height( ui_ContainerGps, 30);
lv_obj_set_x( ui_ContainerGps, 80 );
lv_obj_set_y( ui_ContainerGps, 0 );
lv_obj_set_align( ui_ContainerGps, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_ContainerGps, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_textLocation = lv_label_create(ui_ContainerGps);
lv_obj_set_width( ui_textLocation, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_textLocation, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_textLocation, -23 );
lv_obj_set_y( ui_textLocation, 0 );
lv_obj_set_align( ui_textLocation, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_textLocation,"120'123456 / 21'654321");
lv_obj_set_style_text_color(ui_textLocation, lv_color_hex(0xFCFCFC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_textLocation, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_textLocation, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_imgLocation = lv_img_create(ui_ContainerGps);
lv_img_set_src(ui_imgLocation, &ui_img_1142323638);
lv_obj_set_width( ui_imgLocation, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_imgLocation, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_imgLocation, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_imgLocation, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_imgLocation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_SliderBat, ui_event_SliderBat, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderSpeed, ui_event_SliderSpeed, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_textSpeed, ui_event_textSpeed, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderGyro, ui_event_SliderGyro, LV_EVENT_ALL, NULL);

}
